### ISSUE TITLE
人脸识别类内存泄漏

### ISSUE THREAD

**Issue by zhongwenkun886** [zuoqing1988/ZQCNN#10]
以下为测试代码：

	for (int i = 0; i < 1000; i++)
	{
		std::string prototxt_file =   "./model/model-r50-am.zqparams";
		std::string caffemodel_file = "./model/model-r50-am.nchwbin";
		std::string out_blob_name = "fc5";
		ZQ_FaceRecognizerArcFaceZQCNN* pFaceZQCNN = new ZQ_FaceRecognizerArcFaceZQCNN();
		if (!pFaceZQCNN->Init("", prototxt_file, caffemodel_file, out_blob_name))
		{
			cout << "failed to init arcface\n";
			return 0;
		}
		delete pFaceZQCNN;
	}

每次循环时内存都会上涨，delete pFaceZQCNN 没有完全释放内存。

**Comment by zuoqing1988** [comment]
@zhongwenkun886 
感谢你发现此问题。
内存泄漏注意问题在于析构函数，（1）有些Layer忘了写析构函数，（2）父类析构函数忘了写成virtual
修改代码之后我测了2万次，没有发现明显的内存泄漏（任务管理器内存略有上涨，但是2万次也没涨超过1MB）

**Comment by zhongwenkun886** [comment]
赞!!!!
