### ISSUE TITLE
关于如何运行人头检测模型

### ISSUE THREAD

**Issue by liuxiaoliu321** [zuoqing1988/ZQCNN#109]
尊敬的左老师，您好。最近在学习您的ZQMTCNN人脸和人头检测算法。下载您的ZQCNN代码和人头检测模型参数zqcnn-v0。运行ZQCNN.sln工程后，却发现里面没有关于人头检测的工程，我将您的“人头检测模型”分别放在SampleMTCNN、SampleMTCNNGesture工程下，替换原程序中相关模型，使用您在训练人头检测模型里面的图片head5.jpg作为测试图片，发现均没有检测到人头，烦请老师能够给予解答，如何正确运行人头检测，对您百忙之中，给予解答，非常感谢。

**Comment by zuoqing1988** [comment]
用人头模型替换掉SampleMTCNN里的模型，代码里有多个分支，确保能运行到你想要的分支。
如果没有找到人头，进入Init函数里，把几个LoadFrom里面的true改成false试试。

**Comment by liuxiaoliu321** [comment]
左老师，您好。按照您给出的方法，我已经可以找到人头了。如果我想进一步提高检测人头的精度，请问我可以从哪几个角度出发，进行下一步的工作，烦请老师不惜赐教，谢谢！

**Comment by zuoqing1988** [comment]
主要还是训练数据。我用的训练数据是HollywoodHeads，质量很差。
如果你不太在乎检测时间，可以直接用SSD的一些修改版本，比如refinedet。

**Comment by liuxiaoliu321** [comment]
老师，太感谢您，您真的很热心！
