### ISSUE TITLE
MTCNN+人脸识别同时运行时的问题

### ISSUE THREAD

**Issue by zhongwenkun886** [zuoqing1988/ZQCNN#11]
以下为可复现问题的代码。这里用MTCNN做人脸检测，然后提取人脸的特征，当循环到一定次数时（几百到一千次），人脸检测会失败（mtcnn.Find 函数返回false）。

#include "ZQ_CNN_MTCNN.h"
#include "ZQ_FaceRecognizerArcFaceZQCNN.h"

#include <iostream>
#include "opencv2\opencv.hpp"

#include "ZQ_CNN_ComplieConfig.h"
#if ZQ_CNN_USE_BLAS_GEMM
#include <cblas.h>
#pragma comment(lib,"libopenblas.lib")
#endif

using namespace std;
using namespace cv;
using namespace ZQ;

int main()
{
#if ZQ_CNN_USE_BLAS_GEMM
	openblas_set_num_threads(4);
#endif
	
	for (int i = 0; i<10000;i++)
	{
		printf("i = %d\n", i);
		Mat image0 = cv::imread("data\\AE_.jpg", 1);
		if (image0.empty())
		{
			cout << "empty image\n";
			return EXIT_FAILURE;
		}

		std::string prototxt_file =   "model\\mobilefacenet-v0.zqparams";
		std::string caffemodel_file = "model\\mobilefacenet-v0.nchwbin";
		std::string out_blob_name = "fc5";
		ZQ_FaceRecognizerArcFaceZQCNN* pFaceZQCNN = new ZQ_FaceRecognizerArcFaceZQCNN();
		if (!pFaceZQCNN->Init("", prototxt_file, caffemodel_file, out_blob_name))
		{
			cout << "failed to init arcface\n";
			return 0;
		}

		int FeatureLength = pFaceZQCNN->GetFeatDim();
		float * outFeature = new float[FeatureLength];

		std::vector<ZQ_CNN_BBox> thirdBbox;
		ZQ_CNN_MTCNN mtcnn;

		if (!mtcnn.Init("model\\det1.zqparams", "model\\det1.nchwbin", "model\\det2.zqparams",
			"model\\det2.nchwbin", "model\\det3.zqparams", "model\\det3.nchwbin"))
		{
			cout << "failed to init!\n";
			return EXIT_FAILURE;
		}

		mtcnn.SetPara(image0.cols, image0.rows, 60, 0.6, 0.7, 0.7, 0.5, 0.5, 0.5);
		if (!mtcnn.Find(image0.data, image0.cols, image0.rows, image0.step[0], thirdBbox))
		{
			cout << "failed to find face!\n";
			return EXIT_FAILURE;
		}

		float face5point_x[5] = { 0 };
		float face5point_y[5] = { 0 };

		for (int num = 0; num < 5; num++)
		{
			face5point_x[num] = *(thirdBbox[0].ppoint + num);
			face5point_y[num] = *(thirdBbox[0].ppoint + num + 5);
		}

		Mat NormFace = Mat(pFaceZQCNN->GetCropHeight(), pFaceZQCNN->GetCropWidth(), CV_8UC3);

		pFaceZQCNN->CropImage(image0.data, image0.cols, image0.rows, image0.step[0], ZQ_PIXEL_FMT_BGR, face5point_x, face5point_y,
			(unsigned char*)(NormFace.data), NormFace.step[0]);

		if (!pFaceZQCNN->ExtractFeature((unsigned char*)(NormFace.data), NormFace.step[0],
			ZQ_PIXEL_FMT_BGR, outFeature, true))
		{
			cout << "failed to ExtractFeature!\n";
			return EXIT_FAILURE;
		}

		delete pFaceZQCNN;
		delete[]outFeature;
	}

	return EXIT_SUCCESS;
}

**Comment by zuoqing1988** [comment]
@zhongwenkun886 我把你这代码全部复制下来。
第一次运行i=703时failed to find face
第二次运行到直到结束也没有fail
第三次运行i=3679时failed to find face

我唯一能想到的**可能原因**是 openblas在多线程下每次结果并不完全一样（浮点数组累加顺序不同可能会导致结果略有区别）。

**Comment by zhongwenkun886** [comment]
发现单独做MTCNN人脸检测，同一个输入图片循环一两千次后也会出问题，mtcnn.Find 函数会返回false。以下为可复现问题的代码

#include "ZQ_CNN_MTCNN.h"
#include <iostream>
#include "opencv2\opencv.hpp"

#include "ZQ_CNN_ComplieConfig.h"
#if ZQ_CNN_USE_BLAS_GEMM
#include <cblas.h>
#pragma comment(lib,"libopenblas.lib")
#endif

using namespace std;
using namespace cv;
using namespace ZQ;

int main()
{
#if ZQ_CNN_USE_BLAS_GEMM
	openblas_set_num_threads(4);
#endif
	
	for (int i = 0; i<10000;i++)
	{
		printf("i = %d\n", i);
		Mat image0 = cv::imread("data\\AE_.jpg", 1);
		if (image0.empty())
		{
			cout << "empty image\n";
			return EXIT_FAILURE;
		}

		std::vector<ZQ_CNN_BBox> thirdBbox;
		ZQ_CNN_MTCNN mtcnn;

		if (!mtcnn.Init("model\\det1.zqparams", "model\\det1.nchwbin", "model\\det2.zqparams",
			"model\\det2.nchwbin", "model\\det3.zqparams", "model\\det3.nchwbin"))
		{
			cout << "failed to init!\n";
			return EXIT_FAILURE;
		}

		mtcnn.SetPara(image0.cols, image0.rows, 60, 0.6, 0.7, 0.7, 0.5, 0.5, 0.5);
		if (!mtcnn.Find(image0.data, image0.cols, image0.rows, image0.step[0], thirdBbox))
		{
			cout << "failed to find face!\n";
			return EXIT_FAILURE;
		}
	}

	return EXIT_SUCCESS;
}

**Comment by zuoqing1988** [comment]
![ttt](https://user-images.githubusercontent.com/20920889/45738326-ad778000-bc22-11e8-9369-110280701d19.jpg)
把你刚给的代码运行了5次，都没出问题

**Comment by zhongwenkun886** [comment]
奇怪了，我这里全部循环结束前肯定会出问题，而且我把输入图片换成 4.jpg （四个美女那图），也是会有问题。

**Comment by zhongwenkun886** [comment]
@zuoqing1988 ，opencv_world342.dll 这个文件你是用官方的还是自己重新编译的？我这里是用官网发布编译好的，你的源码中没有提供 opencv_world342.dll ， 所以我这边和你唯一不同的就是这个文件。
