### ISSUE TITLE
请问准商用级106点mxnet的模型转位onnx模型报无法找到自定义操作 negativemining_onlylandmark106

### ISSUE THREAD

**Issue by qaz734913414** [zuoqing1988/ZQCNN#127]
请问准商用级106点mxnet的模型转位onnx模型报无法找到自定义操作 negativemining_onlylandmark106，这种情况该如何处理啊？我用的MMdnn转的

**Comment by zuoqing1988** [comment]
先用train-mtcnn工程用test模式加载该模型，保存之后就没训练的layer

**Comment by qaz734913414** [comment]
已解决，谢谢左博士的指教
