### ISSUE TITLE
我用112*96训练报错了。请问应该怎么修改呢？

### ISSUE THREAD

**Issue by leiyu1980** [zuoqing1988/ZQCNN#13]
我的数据都是112*96大小的，用的 MobileFaceNet-res2-6-10-2-dim256这个训练脚本。我按照 “InsightFace： how to train 112*96“ 这个做了修改。 但是训练的是报了做个错误。。。
请问应该怎么修改呢。。
mxnet.base.MXNetError: [12:15:09] c:\jenkins\workspace\mxnet-tag\mxnet\src\operator\tensor\./matrix_op-inl.h:659: Check failed: e <= len (104 vs. 96) slicing with end[1]=104 exceeds limit of 96

**Comment by zuoqing1988** [comment]
我更改的原理是在112*112图片里面取一个roi，python脚本里是img = img[:,8:104,:]，而如果你的图片本身就是112*96，那么就不需要取roi的这句了

**Comment by zuoqing1988** [comment]
你想保留取roi的话，就改成img=img[:,0:96,:];

**Comment by leiyu1980** [comment]
明白了。原来是这样。那我就不用保留roi了。
