### ISSUE TITLE
68个点是怎样进行仿射变换得到对齐人脸的呢？

### ISSUE THREAD

**Issue by bleakie** [zuoqing1988/ZQCNN#130]
请教左博，我现在使用的是68个关键点，根据这些怎样得到对齐后的人脸呢？Dlib的总觉得仿射变换后的脸有点怪？

**Comment by zuoqing1988** [comment]
取对应的5点

**Comment by zuoqing1988** [comment]
训练数据是5点对齐的，如果你想重新造数据也行
最大的开源数据集上112X112比96X112性价比更高

**Comment by bleakie** [comment]
感谢左博的耐心指导，请问如果我想训练人证识别，现在我有人证照片大约20w组，我用ms1m的预训练，用人证照片进行调优，效果不理想
请教，我怎样可以针对人证识别得到更好的效果呢？

**Comment by zuoqing1988** [comment]
你自己的训练集太小，怎么也得几百万上千万才行

**Comment by bleakie** [comment]
这就尴尬了，我用自己的模型和云从买的sdk比对，发现云从的确实稳定，但是在图片质量不高的情况下，也不行
