### ISSUE TITLE
移植到安卓上的性能损失问题

### ISSUE THREAD

**Issue by DanielMao2015** [zuoqing1988/ZQCNN#132]
左博你好，我将MTCNN的ZQCNN版本移植移植到安卓上之后，发现针对320*240的图片，需要大概70ms的时间完成（骁龙845处理器），和pc端相比的性能损失，主要是哪一块带来的呢？是GEMM算法的改变吗？ 
  另外想请教你一下，关于基于神经网络的人脸检测和对齐方法，在手机端上目前是否有实用价值呢，目前现有的采用人脸跟踪的方式能做到10ms以内，不知道深度学习的方式是否有这样的能力。

**Comment by zuoqing1988** [comment]
我们在手机上，单核A53。视频逐帧找人脸+106点landmark，每张脸小于10ms

**Comment by zuoqing1988** [comment]
开源的就是随便玩玩，和商用还有鸿沟

**Comment by DanielMao2015** [comment]
@zuoqing1988 谢谢左博！
