### ISSUE TITLE
怎么运行SamplesZQCNN?

### ISSUE THREAD

**Issue by Liujinglin03** [zuoqing1988/ZQCNN#134]
导师说用ZQCNN做人脸识别，我在ubuntu系统下根据指令
mkdir cmake-build-release && cd cmake-build-release
cmake .. 
make -j4
编译完成了，但是下一步编译运行SamplesZQCNN时，不知道怎么实现识别程序，查询网络后，也没找到相关指导，左老师能告诉怎么实现吗？
其中在/ZQCNN/SampilesZQCNN/文件中make不成功，出现“fatal error: ZQ_CNN_Net.h: 没有那个文件或目录#include "ZQ_CNN_Net.h" ”问题。

**Comment by zuoqing1988** [comment]
先在windows下用VS2015编译吧

**Comment by Liujinglin03** [comment]
谢谢大佬

**Comment by isdotjim** [comment]
搭个车...
想邀请Repo作者来w3c.group创建项目的对应小组。w3c.group是类似知识星球的社群工具，小组可设置为付费且有赞助功能，同时也是一个区块链主导的创作者社区。这是相关介绍：
http://t.cn/Ai1vLcCU
http://t.cn/Ai1vLcCG
http://t.cn/Ai1vLcCA
