### ISSUE TITLE
你好，左博，请问106点是Pnet、Rnet、Onet后获得的人脸作为Lnet输入训练的？

### ISSUE THREAD

**Issue by cml773** [zuoqing1988/ZQCNN#135]
请问一下，我想自己训练106点，该从哪里入手？

**Comment by zuoqing1988** [comment]
嗯。
用其他检测器也行

**Comment by cml773** [comment]
请问，调用train_L_net_onlylandmark106.py 训练106点模型，并且用您提供的数据集106data_merge，训练后的得到的模型效果如何，是否与您提供的准商用106点模型网络层次结构一样，效果相差多少

**Comment by zuoqing1988** [comment]
模型结构一样，效果应该差很多。

**Comment by cml773** [comment]
我用上面训练的模型，调用demo106.py加载的时候出现错误

ValueError: Find name "conv1_weight" that is not in the arguments

**Comment by zuoqing1988** [comment]
因为商业机密的问题，现在整个训练项目我都删掉了，以后靠你自己琢磨了

**Comment by cml773** [comment]
有问题可否请教  能否加个QQ

**Comment by zuoqing1988** [comment]
275918592

**Comment by cml773** [comment]
谢谢左博
