### ISSUE TITLE
支持32位x86吗

### ISSUE THREAD

**Issue by xinheblue** [zuoqing1988/ZQCNN#141]
想做一个应用，希望能支持XP用户，请问下左博，咱们的ZQCNN支持x86,从而可以部署到xp上吗

**Comment by zuoqing1988** [comment]
应该支持，最多需要稍微改点东西，以前有人在32位系统里用过

**Comment by xinheblue** [comment]
> 应该支持，最多需要稍微改点东西，以前有人在32位系统里用过

多谢左博，我试一下
