### ISSUE TITLE
mkl库不支持32位系统，想在32位系统用ZQCNN，有啥办法

### ISSUE THREAD

**Issue by xinheblue** [zuoqing1988/ZQCNN#143]
如issue, https://github.com/intel/mkl-dnn/issues/639 https://github.com/intel/mkl-dnn/issues/180 mkl不支持32位库，也不打算支持
在这种情况下，还是想在xp系统用ZQCNN，有啥替代解决办法

**Comment by zuoqing1988** [comment]
用Openblas或者ZQ_GEMM
https://github.com/zuoqing1988/ZQCNN/blob/5d84c96310d38d174c8a7036aa1eaf2937073632/ZQCNN/ZQ_CNN_CompileConfig.h#L22

**Comment by xinheblue** [comment]
多谢大神
