### ISSUE TITLE
请问移植到mips，需要移植的内容有哪些，需要注意哪些地方？谢谢

### ISSUE THREAD

**Issue by lanliqiang** [zuoqing1988/ZQCNN#144]
很高兴使用您开源的软件，速度和质量都很完美，谢谢。近期，要实现国产化的任务，采用的芯片是龙芯的CPU，指令集是MIPS。请问移植到mips，需要移植的内容有哪些，需要注意哪些地方？谢谢

**Comment by zuoqing1988** [comment]
最早用的SSE/AVX指令，后面用Neon也是通过宏定义替换了SSE/AVX

**Comment by lanliqiang** [comment]
谢谢，多谢你的指教。
我会从ZQ_CNN_CompileConfig.h文件中定义的宏入手，依次替换宏定义的点。
新年快乐。来年有问题，希望多多帮助，谢谢。

**Comment by lanliqiang** [comment]
谢谢，多谢你的指点。
我会从ZQ_CNN_CompileConfig.h这个文件的宏入手，依次修改CPU相关指令。
新年快乐，谢谢。
