### ISSUE TITLE
Questions about inference speed of arcface-r50

### ISSUE THREAD

**Issue by WANG-MengJiao** [zuoqing1988/ZQCNN#16]
Hi, there. Thank you for share this work. I have some questions about the inference time speed. The inference time table says arcface-r50 will take about 700ms on 3.6GHz CPU. I am wondering how this result is tested. To be specific, did you just use ZQCNN for acceleration? Or did you also use other library, like OpenMP or MKL-DNN, etc?

**Comment by zuoqing1988** [comment]
all models are tested by zqcnn on e5 1650 v4 3.6GHz, single thread.

**Comment by zuoqing1988** [comment]
Using MKL , arcface-r50 costs only 175ms, single thread.
