### ISSUE TITLE
SSE指令集错误：Illgeal Instruction

### ISSUE THREAD

**Issue by fawdlstty** [zuoqing1988/ZQCNN#162]
cpu型号：i5 3470
指令集（CPU-z）：MMX，SSE，SSE2，SSE3，SSSE3，SSE4.1，SSE4.2，EM64T，VT-x，AES，AVX
修改 `ZQ_CNN_CompileConfig.h` 中`ZQ_CNN_USE_SSETYPE`的值为 `ZQ_CNN_SSETYPE_SSE`
然后运行SampleMTCNN项目，报错，错误位置位于`zq_cnn_resize_32f_align_c_raw.h`中的`cur_sx = zq_mm_set1_ps(sx[w]);`，提示Illgeal Instruction
经查，宏定义`zq_mm_set1_ps`最终转向`_mm_set_ps1`，反汇编结果为：
```asm
					cur_sx = zq_mm_set1_ps(sx[w]);
000000013F3A7425 48 63 85 04 03 00 00 movsxd      rax,dword ptr [w]  
000000013F3A742C 48 8B 4D 48          mov         rcx,qword ptr [sx]  
000000013F3A7430 C5 FA 10 04 81       vmovss      xmm0,dword ptr [rcx+rax*4]  
000000013F3A7435 C4 E2 79 18 C0       vbroadcastss xmm0,xmm0  
000000013F3A743A C5 F8 11 85 90 03 00 00 vmovups     xmmword ptr [cur_sx],xmm0  
```
崩溃时黄色箭头（当前崩溃点）位于vbroadcastss这一行

**Comment by zuoqing1988** [comment]
试试修改项目属性里 C/C++-->代码生成-->启动指令集

**Comment by fawdlstty** [comment]
有六个选项：SSE、SSE2、AVX、AVX2、无增强指令、未设置，都试过了，都不行

**Comment by fawdlstty** [comment]
编译输出：`cl : 命令行 warning D9002: 忽略未知选项“/arch:SSE2”`

**Comment by zuoqing1988** [comment]
试试用AVX编译，注意不只是SampleMTCNN项目属性要改，ZQCNN也要改，如果用了ZQGEMM那么ZQGEMM也要改

**Comment by fawdlstty** [comment]
谢谢，可以了，设置错误
