### ISSUE TITLE
新版本106关键点中眉毛和嘴巴的点比例较其他点小了一倍

### ISSUE THREAD

**Issue by suzj-hash** [zuoqing1988/ZQCNN#172]
左大佬好，
图1为2019年10月23日的版本，106点位置正常。图2为2021年11月23日的版本，106点中眉毛和嘴巴的点比例尺比其他点的小了一倍。两个版本都开启了ZQ_CNN_USE_ZQ_GEMM，使用的vs2017，但用的是2015的工具集。
![image](https://user-images.githubusercontent.com/56944489/143414140-519f7735-efe5-43b2-aa51-ef8e1f12129d.png)
                                                                                          图1

![image](https://user-images.githubusercontent.com/56944489/143416383-10fecefd-efe4-4494-ad90-c21b1050c7c2.png)
                                                                                          图2

**Comment by zuoqing1988** [comment]
每个版本训练的landmark在数据增强的时候不同，最好运行SampleMTCNN，不要直接测试landmark

**Comment by suzj-hash** [comment]
左大佬，在SampleMTCNN中的以下函数中的thread_num>1时，将发生上文提到的现象。
mtcnn.Init("model/det1-dw20-fast.zqparams", "model/det1-dw20-fast.nchwbin",
				"model/det2-dw24-fast.zqparams", "model/det2-dw24-fast.nchwbin",
				//"model\\det2.zqparams", "model\\det2_bgr.nchwbin",
				"model/det3-dw48-fast.zqparams", "model/det3-dw48-fast.nchwbin",
				//"model/det3.zqparams", "model/det3_bgr.nchwbin",
				thread_num, false,
				"model/det4-dw48-v2n.zqparams", "model/det4-dw48-v2n.nchwbin"
				//"model/det3.zqparams", "model/det3_bgr.nchwbin"）

**Comment by zuoqing1988** [comment]
如果是因为多线程造成的，多半是因为VS2017的openmp和VS2015有区别，以前也发生过这种现象

**Comment by suzj-hash** [comment]
我下载vs2015和opencv342使用，解决方案平台为x64，但无论解决方案配置是debug还是release，运行SampleMTCNN得到的结果如下图。
![image](https://user-images.githubusercontent.com/56944489/143818193-abe92602-b618-4400-8cad-25ff0566a8e0.png)

**Comment by zuoqing1988** [comment]
你可能自己改了代码不知道，重新拉新的，我在windows和linux都正常

**Comment by suzj-hash** [comment]
我删除了旧的ZQCNN文件夹，拉取了新的git代码，并做了一下改动：
1.ZQ_CNN_CompileConfig.h中#define ZQ_CNN_USE_MKL_GEMM 1改为0 （目的启用ZQ_CNN_USE_ZQ_GEMM）
2.将opencv_world342.dll置于根目录下。
3.改动SampleMTCNN中的thread_num = 0改为2
结果依旧异常，另外，我电脑中同时存在vs2017和vs2015，这会不会有影响？

**Comment by suzj-hash** [comment]
我尝试了使用mkl，结果同样异常，改动如下：
1.将opencv_world342.dll、mklml.dll、libiomp5md.dll置于根目录下。
2.改动SampleMTCNN中的thread_num = 0改为2
我再尝试下仅且重装vs2015的情况。

**Comment by sxl1007** [comment]
> 
你好！请问你在vs2015中使用的openmp库是哪个版本？
我看vs2015下似乎有多个版本：
VC110_OpenMP、VC120_OpenMP、VC140_OpenMP。
vs2017中只有一个版本：
VC140_OpenMP。

参考：
https://docs.microsoft.com/zh-cn/visualstudio/releases/2015/2015-redistribution-vs
https://docs.microsoft.com/zh-cn/visualstudio/releases/2017/2017-redistribution-vs

**Comment by sxl1007** [comment]
> 你可能自己改了代码不知道，重新拉新的，我在windows和linux都正常



> 如果是因为多线程造成的，多半是因为VS2017的openmp和VS2015有区别，以前也发生过这种现象

> 
你好！请问你在vs2015中使用的openmp库是哪个版本？
我看vs2015下似乎有多个版本：
VC110_OpenMP、VC120_OpenMP、VC140_OpenMP。
vs2017中只有一个版本：
VC140_OpenMP。

参考：
https://docs.microsoft.com/zh-cn/visualstudio/releases/2015/2015-redistribution-vs
https://docs.microsoft.com/zh-cn/visualstudio/releases/2017/2017-redistribution-vs

**Comment by zuoqing1988** [comment]
![image](https://user-images.githubusercontent.com/20920889/143985165-0ead630e-f99a-46ba-b3c3-92948d7cbf19.png)
VS2015里只有是否支持openmp，没有版本选择

**Comment by zuoqing1988** [comment]
@suzj-hash @sxl1007 
openmp造成的问题可能是某些变量本应该是各个线程独立的但是事实上互相干扰了,如果你们在你们的编程环境下改正确了,可以告诉我,或者你们提交一个pull request.

**Comment by suzj-hash** [comment]
https://github.com/zuoqing1988/ZQCNN/blob/4eb8250d2a9aa789788aa344bc81a5c86d60f3ea/ZQCNN/ZQ_CNN_MTCNN.h#L1740
https://github.com/zuoqing1988/ZQCNN/blob/4eb8250d2a9aa789788aa344bc81a5c86d60f3ea/ZQCNN/ZQ_CNN_MTCNN.h#L1742
以上两行最后的   *0.5  注释后异常消失了。

**Comment by zuoqing1988** [comment]
@suzj-hash 非常感谢。这个错误应该是我先前换模型调试之后没统一
