### ISSUE TITLE
Some questions about model GenderAge-r50 

### ISSUE THREAD

**Issue by Rainy000** [zuoqing1988/ZQCNN#21]
I convert the mxnet model of GenderAge-r50  according to wiki, and compile the sample of GenderAge sucessfully. But I found that all face image(3*112*112) get the result of 28/29 age and Male.

**Comment by zuoqing1988** [comment]
**Reason**: the zqparams file generated by mxnet2zqcnn.exe may have two scalaroperation layers. 

**Solution1**: delete them
for example:
`Input            name=data 
ScalarOperation operation=minus name=_minusscalar0  bottom=data top=_minusscalar0 scalar=127.500000
ScalarOperation operation=mul name=_mulscalar0  bottom=_minusscalar0 top=_mulscalar0 scalar=0.007813
Convolution      name=conv_1_conv2d  bottom=_mulscalar0 top=conv_1_conv2d num_output=64 kernel_H=3 kernel_W=3 stride_H=2 stride_W=2 pad_H=1 pad_W=1`
changed to 
`Input            name=data 
Convolution      name=conv_1_conv2d  bottom=data top=conv_1_conv2d num_output=64 kernel_H=3 kernel_W=3 stride_H=2 stride_W=2 pad_H=1 pad_W=1`

**Solution2**: set mean=0 and scale=1 in ZQ_CNN_Tensor::ConvertFromBGR
for example
`ZQ_CNN_Tensor4D_NHW_C_Align128bit input;
input.ConvertFromBGR(image.data, image.cols, image.rows, image.step[0]);`
changed to 
`ZQ_CNN_Tensor4D_NHW_C_Align128bit input;
input.ConvertFromBGR(image.data, image.cols, image.rows, image.step[0],0,1);`

**Comment by Rainy000** [comment]
wow, it's preprocessing problem. That's great, thank you!

**Comment by zuoqing1988** [comment]
@Rainy000 这个模型虽然ZQCNN和ncnn算的结果接近，但是我总觉得不对

**Comment by Rainy000** [comment]
@zuoqing1988  It's to slowly and I only test a few images, so just found the model too stable for any face,the swing value almost around [-3,3] .

**Comment by Rainy000** [comment]
@zuoqing1988  Thank you! I also heard that. I train one GenderAge model based on mobilefacenet and costs 50ms on minicaffe. If it can run faster  when convert your ZQCNN  on theory?

**Comment by Rainy000** [comment]
@zuoqing1988 oh I  forget my model trained base on CAFFE..

**Comment by zuoqing1988** [comment]
It will speedup by 1.5-2.0. 
mobilefacenet costs around 30ms testing on E5-1650 V4 3.6GHz, single thread.
You can firstly convert from caffe to mxnet, and then convert to ZQCNN.

**Comment by zuoqing1988** [comment]
使用最新版ZQCNN，支持MKL，是之前使用OpenBLAS的接近三倍。也可以使用ZQ_GEMM，是之前使用OpenBLAS的接近两倍。

**Comment by Rainy000** [comment]
@zuoqing1988  左博V587!
