### ISSUE TITLE
SSE AVX 编译问题

### ISSUE THREAD

**Issue by w136111526** [zuoqing1988/ZQCNN#23]
我把你的 ZQ_CNN_USE_SSETYPE 改为 ZQ_CNN_SSETYPE_AVX，编译zq_cnn_relu_32f_align_c.c这个文件时报错了，用ZQ_CNN_SSETYPE_AVX2编译就不会报错。是不是你程序那个地方使用了#undef导致报错了啊？下面是vs2015编译信息：
zq_cnn_prelu_32f_align_c.c
1>  zq_cnn_relu_32f_align_c.c
1>e:\publicsvn\zqcnn-v0.0\trunk\zqcnn\layers_c\zq_cnn_relu_32f_align_c_raw.h(213): warning C4013: “zq_mm_fmadd_ps”未定义；假设外部返回 int
1>e:\publicsvn\zqcnn-v0.0\trunk\zqcnn\layers_c\zq_cnn_relu_32f_align_c_raw.h(213): error C2440: “函数”: 无法从“int”转换为“__m256”
1>e:\publicsvn\zqcnn-v0.0\trunk\zqcnn\layers_c\zq_cnn_relu_32f_align_c_raw.h(213): warning C4024: “_mm256_store_ps”: 形参和实参 2 的类型不同
1>e:\publicsvn\zqcnn-v0.0\trunk\zqcnn\layers_c\zq_cnn_relu_32f_align_c_raw.h(216): error C2440: “函数”: 无法从“int”转换为“__m256”

**Comment by zuoqing1988** [comment]
找到问题了
把zq_mm_fmadd_ps 写成了zq_mm256_fmadd_ps

**Comment by w136111526** [comment]
只有zq_cnn_relu_32f_align_c.c这一个文件写错了吧，我能编译过了

**Comment by zuoqing1988** [comment]
MKL_set_num_threads(1);
视频解码如果用Opencv的话，设置线程数好像也还是会消耗超过一个线程
