### ISSUE TITLE
ZQCNN移植到linux系统下，运行时出错

### ISSUE THREAD

**Issue by cvtuge** [zuoqing1988/ZQCNN#24]
移植到linux系统下，运行SampleSphereFaceNet在执行ZQ::ZQ_CNN_Tensor4D::ConvertFromBGR时会挂掉

如果	
ZQ_CNN_Tensor4D_NHW_C_Align128bit input0, input1 
改为 ZQ_CNN_Tensor4D_NHW_C_Align0 input0,input1; 
就没问题，这是为什么呢，ZQCNN以后会出linux版本的吗？

**Comment by zuoqing1988** [comment]
1.短期内还是以提升性能，添加layer支持为主。不过如果你只用ZQCNN.sln里面的功能，移植到linux应该还是很简单。
2.你用你版本应该不是最新的了，我几乎每周都更新很多次。
3.如果在windows确认执行正确，换到Linux崩溃，可能是机器不支持AVX2，你可以试试把ZQ_CNN_CompileConfig.h里的设置改一改。

**Comment by zuoqing1988** [comment]
我刚把代码改了改，在linux环境下只编译ZQCNN.a的话你不需要改动任何代码了。
不过我是在虚拟机环境下试的，没有SSE/AVX，没有OpenBLAS、MKL。

**Comment by zuoqing1988** [comment]
@cvtuge 现在能在linux编译通过了，速度和windows下差不多
