### ISSUE TITLE
mxnet 模型转成caffe 输出不一致

### ISSUE THREAD

**Issue by karlTUM** [zuoqing1988/ZQCNN#26]
您好，
我用了您的mxnet2caffe 代码转换了mobilefacenet模型 运用check results 发现输出的结果不一样，想请教一下大神，哪里有问题

```
[
[[ 0.017276   -0.4222807  -0.07165871  0.7135863  -0.12447087  0.06586622
  -0.16812389 -0.13903007  0.04360439 -0.22122525  0.0435597   0.11936011
  -0.23474081 -0.3577653  -0.1679546  -0.13885504  0.16633391  0.25873622
  -0.33021694 -0.11786669 -0.02872146 -0.477086   -0.11106284  0.11695821
  -0.12934922  0.255884   -0.1942169   0.12630616 -0.23865224  0.18448791
   0.10559033 -0.088712   -0.04691517  0.26358733  0.18018812  0.14805603
  -0.2553117   0.5503354   0.5195001  -0.34429112 -0.50690997  0.46173176
   0.3151336   0.02643948 -0.2646044  -0.13466054 -0.02762383  0.37433448
  -0.44442838 -0.14106162 -0.03115291 -0.7350194  -0.55731094  0.02851256
  -0.01867473 -0.22451565  0.0659817   0.03267149 -0.07442598 -0.00755793
  -0.05205738  0.04383722  0.42879567 -0.25555742 -0.23541915  0.41604832
  -0.06175407 -0.2166583  -0.14290327 -0.01595623  0.64858043 -0.13120429
  -0.19330469 -0.2647119   0.02685797  0.38061866  0.1258779  -0.1579753
   0.01175252 -0.3725114  -0.4544143   0.2203731   0.07688574 -0.19915707
  -0.05907691 -0.26913345  0.12543568  0.20025031 -0.2774456   0.12992482
   0.0010437   0.06121505  0.1540927   0.10459166  0.08840342  0.43114156
   0.17922197 -0.493483   -0.7070367  -0.5172252  -0.46376437 -0.29713553
  -0.03089709  0.47260872  0.22349297  0.19986378  0.2616748   0.1465985
   0.1783604  -0.23194014  0.10261983  0.21745919  0.4326741  -0.04612612
   0.6061288   0.34292504  0.51188225 -0.23691243  0.13759308 -0.22194609
  -0.5215853  -0.13520943 -0.18358245  0.13728186 -0.27748924  0.07769431
  -0.33542892  0.42282426]]
<NDArray 1x128 @cpu(0)>]
[[ 6.2732756e-02 -5.9952173e-02  2.2413557e-02 -3.1469498e-02
   6.5951027e-02 -2.8367542e-02  3.2204002e-02  7.7424929e-02
  -9.7055621e-02 -6.9253430e-02 -4.5930523e-02 -7.6132409e-02
  -5.0844617e-02 -6.4346619e-02 -1.5729671e-02  5.3271189e-02
   5.3257262e-04 -5.2365875e-03  1.4655352e-02 -4.3126322e-02
  -1.0661008e-02 -8.7465690e-03 -2.8252389e-02 -7.0996016e-02
  -1.9464381e-03 -2.8986113e-02 -3.6444955e-02  3.6922205e-02
  -3.8776599e-02 -3.2794930e-02 -9.8875435e-03  6.2595280e-03
  -5.0185490e-03 -3.4949131e-02  4.1359983e-02  3.1499282e-02
  -2.8646499e-02 -5.9114099e-02  1.7148184e-02 -4.8444647e-02
  -9.7029276e-02  4.4342317e-04 -2.7198687e-02 -2.8752765e-02
   4.1433349e-02  1.2933503e-02 -4.9672965e-02 -3.5463576e-03
   4.7990292e-02  2.5810581e-03  3.1260908e-02  1.5094576e-02
  -1.3907658e-02 -2.7079349e-03  5.8484511e-03 -1.4168183e-02
   1.7932409e-02 -3.7768781e-02 -1.8586438e-02 -1.0990779e-02
  -4.7573805e-02 -5.8607054e-03 -4.9528219e-02 -2.2688817e-02
  -6.9002919e-02 -2.1926099e-03 -3.6008663e-02 -2.7441682e-02
  -2.9889676e-03 -3.6228251e-02 -8.7704889e-02 -3.7730277e-02
   4.5867212e-02 -1.6259417e-02  6.2029455e-03 -1.7036878e-02
  -3.9387021e-02  1.5584700e-02  3.4619402e-03 -4.7294483e-02
  -4.2392161e-02 -6.7054451e-02 -3.1520490e-02 -1.1477423e-01
   7.1737356e-03  5.5631641e-02  4.3232810e-02 -2.7725386e-02
   3.7312735e-02  1.1762280e-02 -1.0883956e-01  4.5307346e-02
  -3.2287091e-02 -1.7094158e-02 -1.6419319e-02 -3.3274885e-02
  -3.8385842e-02  4.6371106e-02 -4.4565663e-02  1.4135682e-02
  -2.6000340e-02 -4.3430896e-03 -5.8525845e-02  2.6870819e-02
  -1.5334387e-02  2.2968277e-05  6.3471328e-03 -4.4829208e-02
  -1.8722905e-02 -1.7468868e-02 -5.2707534e-02  3.7894405e-02
  -1.9262727e-02  7.9293303e-02 -2.5021762e-02  2.7414378e-02
   2.9555865e-02 -2.5431961e-03 -7.2565585e-02  3.5143670e-02
   4.9341552e-02 -8.4194131e-02  4.3513231e-02 -2.1488478e-03
  -2.2843815e-03  4.7319688e-02  6.3874900e-02  1.4988746e-02]]
```
前一个为mxnet输出结果， 后一个为caffe model输出结果

我首先运用

json2prototxt.py 转换json到prototxt
再在生成的prototxt文件中改了 bottom: “_mulscalar0”，将_mulscalar0改为上一层的”data”.

然后运用 mxnet2caffe.py 转换mxnet model 到caffe model

再就用 check_results.py 来输出结果如上，发现生成的128维embedding不同，
多谢大神指教

**Comment by karlTUM** [comment]
而且我发现更改输入tensor, caffe model一直输出同一个结果

**Comment by zuoqing1988** [comment]
你转完模型之后用ZQlibFaceID.sln里的程序SampleEvaluationOnLFWArcFaceOpenCV测一下LFW精度
如果精度在99%以上说明转换成功，否则转换失败

**Comment by zuoqing1988** [comment]
你找个windows机器，直接双击mxnet2caffe.bat就行了，不要搞那么麻烦

**Comment by karlTUM** [comment]
@zuoqing1988  请问.bat作用就是修改第一个 "_mulscalar0" 为"data"呗？不行我就在windows重新装一遍

**Comment by zuoqing1988** [comment]
如果是你caffe版本的问题，你可以用我的caffe-ZQ
在windows下很容易编译

**Comment by wjr1990** [comment]
你好，我使用你的脚本转完模型，测试的时候发现所有图像的特征向量完全一样，请问有可能是什么原因呢？谢谢

**Comment by wjr1990** [comment]
@karlTUM 你好，请问你的问题解决了吗？我也v遇到了相同的问题

**Comment by karlTUM** [comment]
@wjr1990 没有 我还没有测试，手头没有windows电脑，我的是linux的。可能是caffe版本的问题？

**Comment by wjr1990** [comment]
> @wjr1990 没有 我还没有测试，手头没有windows电脑，我的是linux的。可能是caffe版本的问题？

我找到问题了，在mxnet2caffe.py这个文件中有一处需要修改，问题是mxnet的fc1_weight中的weight部分的值没有读到，caffemodel对应部分值全是0。

    elif '_weight' in key_i:
      key_caffe = key_i.replace('_weight','')
      if 'fc' in key_i:
        key_caffe = "pre_"+key_caffe

**Comment by WIll-Xu35** [comment]
@wjr1990 @karlTUM 
我尝试用mxnet2caffe转换mxnet的insightface，遇到了同样的问题。
在prototxt修改了“_mulscalar0”和一个dropout的输入之后，能够生成caffemodel，但是永远输出同样的结果，无论输入是什么。
在修改了mxnet2caffe.py之后也还是无论输入是什么，都输出同样的结果。

**Comment by wjr1990** [comment]
> @wjr1990 @karlTUM
> 我尝试用mxnet2caffe转换mxnet的insightface，遇到了同样的问题。
> 在prototxt修改了“_mulscalar0”和一个dropout的输入之后，能够生成caffemodel，但是永远输出同样的结果，无论输入是什么。
> 在修改了mxnet2caffe.py之后也还是无论输入是什么，都输出同样的结果。

你可以尝试着读一下caffemodel最后几层的参数，应该是某些层的weights没读到，默认为0，计算时相当于0*上层输出+bias，所以输出没有变

**Comment by zuoqing1988** [comment]
@karlTUM @wjr1990 @WIll-Xu35 所有之前转不成功和还没开始转的人先试试:

1.从这里https://pan.baidu.com/s/11eV1SccQbTXNV-2tuFBtCw下载模型，然后放在文件夹mobilefacenet-mxnet2caffe-ZQ中

2.修改mxnet2caffe.bat中prefix=model

3.双击mxnet2caffe.bat

4.将生成的模型用ZQlibFaceID.sln里的SampleEvaluationOnLFWArcFaceOpenCV程序测试(请仔细阅读代码查看如何测试LFW精度)，或者用你自己的程序测试LFW精度

**Comment by MrWwei** [comment]
> @wjr1990 @karlTUM
> 我尝试用mxnet2caffe转换mxnet的insightface，遇到了同样的问题。
> 在prototxt修改了“_mulscalar0”和一个dropout的输入之后，能够生成caffemodel，但是永远输出同样的结果，无论输入是什么。
> 在修改了mxnet2caffe.py之后也还是无论输入是什么，都输出同样的结果。

你好，这个问题解决了吗？我用的也是linux

**Comment by MrWwei** [comment]
> @karlTUM @wjr1990 @WIll-Xu35 所有之前转不成功和还没开始转的人先试试:
> 
> 1.从这里https://pan.baidu.com/s/11eV1SccQbTXNV-2tuFBtCw 下载模型，然后放在文件夹mobilefacenet-mxnet2caffe-ZQ中
> 
> 2.修改mxnet2caffe.bat中prefix=model
> 
> 3.双击mxnet2caffe.bat
> 
> 4.将生成的模型用ZQlibFaceID.sln里的SampleEvaluationOnLFWArcFaceOpenCV程序测试(请仔细阅读代码查看如何测试LFW精度)，或者用你自己的程序测试LFW精度

我尝试在windows系统下用您的bat脚本转换成功，但还是出现同样的问题，caffe模型每次输出同样的结果。
