### ISSUE TITLE
运行时报错

### ISSUE THREAD

**Issue by w136111526** [zuoqing1988/ZQCNN#3]
我更新了你的ZQCNN库，用VS2015调试了一下你的SampleMTCNN代码，在执行函数zq_cnn_conv_no_padding_32f_kernel3x3_C3_omp时报错了，提示Illegal Instruction，是我本机不支持AVX向量扩展么，还是需要安装些别的东西啊？

**Comment by zuoqing1988** [comment]
@w136111526 代码使用了AVX2.0，三四年以前的CPU应该会直接崩溃

**Comment by w136111526** [comment]
写一段代码测试一下我电脑确实不支持_mm256_fmadd_ps的AVX2指令，我能用_mm256_add_ps(_mm256_mul(A, B), C)代替 卷积中的_mm256_fmadd_ps（A, B, C）么？

**Comment by w136111526** [comment]
我刚才调通了你的程序，图片大小为640*480，把人脸大小设置为30速度达到了140ms,哪个地方还有优化的空间呀？

**Comment by leiyu1980** [comment]
zqcnn 可以整机支持到 sse4.2吗？

**Comment by leiyu1980** [comment]
zqcnn 可以增加支持到 sse4.2吗？

**Comment by w136111526** [comment]
一般的机器可以支持到AVX

**Comment by zuoqing1988** [comment]
@leiyu1980 @w136111526 必须要AVX2.0，至于是哪个指令造成的我也不清楚，一般的I5，I7应该都能运行。我的台式机是E5-1650V4，还有一个笔记本是I5的。
@leiyu1980 退到SSE4.2属于降级了，未来也只会考虑AVX512，毕竟I5，I7也出来三四年了。ZQCNN主打的是台式机而不是手机。

**Comment by w136111526** [comment]
@zuoqing1988 @leiyu1980 ，我已经调通了哦，公司电脑都是10年以前的老电脑，_mm256_fmadd_ps,_mm_fmadd_ps,老电脑都不支持，需要用SSE2替换掉这两个指令。

**Comment by zuoqing1988** [comment]
@w136111526 对于大部分模型来说，gemm占的时间超过90%，只有depthwise convolution多的模型才能稍微快那么一点点。

**Comment by leiyu1980** [comment]
@zuoqing1988  sse4.2 主要是用在j1900 这一类cpu上。
@w136111526 你修改得部分能放上来吗？

**Comment by leiyu1980** [comment]
@w136111526 好的。我试试

**Comment by zuoqing1988** [comment]
@w136111526 @leiyu1980 我把这个宏加到了代码。在ZQ_CNN_CompileConfig.h里设置

**Comment by w136111526** [comment]
@zuoqing1988 有空我测试下你得代码，最近把你这个zqcnn改的面目全非了，原本想把FindFace改成线程安全的函数，发现ZQ_CNN_Layer东西太多确实不好改动。
