### ISSUE TITLE
a small bug

### ISSUE THREAD

**Issue by wzhiyuan2016** [zuoqing1988/ZQCNN#31]
在pnet，采用修改之前的计算方式：计算mapH 和mapW尺寸 和 pnet[0].Forward(pnet_images[i])计算出来的 scoreH = score->GetH(); scoreW = score->GetW();尺寸维度不相同。
修改之后的计算正常了。
void _compute_Pnet_single_thread(std::vector<std::vector<float>>& maps, 
			std::vector<int>& mapH, std::vector<int>& mapW)
		{
			int scale_num = 0;
			for (int i = 0; i < scales.size(); i++)
			{
				int changedH = (int)ceil(height*scales[i]);
				int changedW = (int)ceil(width*scales[i]);
				if (changedH < pnet_size || changedW < pnet_size)
					continue;
				scale_num++;
                                修改之前：
				mapH.push_back((changedH - pnet_size) / pnet_stride + 1);
				mapW.push_back((changedW - pnet_size) / pnet_stride + 1);*/
                                修改之后：
				mapH.push_back((int)ceil((changedH - pnet_size)*1.0 / pnet_stride) + 1);
				mapW.push_back((int)ceil((changedW - pnet_size)*1.0 / pnet_stride) + 1);
			}
}
测试图片：
data\\keliamoniz1.jpg 640x480
修改之前结果显示：			
![1](https://user-images.githubusercontent.com/33740622/50732071-0bb67780-11ae-11e9-81ce-dda496182535.png)
修改之后结果显示：
![2](https://user-images.githubusercontent.com/33740622/50732076-212ba180-11ae-11e9-9d8a-190b488b4d84.png)

**Comment by zuoqing1988** [comment]
以下内容可能是我当初的设计思路(如果你有时间的话可以帮我验证一下):

我印象中mapH，mapW应该是小于等于scoreH,scoreW，也就是最右侧最下侧可能丢掉一些框。不知道你有没有对比过你修改前后的检测结果，应该没有什么区别吧？

这么设计的原因是我不确定pnet可能会有哪些层，比如同一层用pooling和dwconv出来的长宽是不一样的。
如果要准确计算输出的长宽需要先forward算一次，如果每帧图片大小或者min size都不一样，这会带来很大的额外开销。

**Comment by zuoqing1988** [comment]
你现在的执行路径是pnet_size=12，你试试执行pnet20那个分支，看是否崩掉?

**Comment by wzhiyuan2016** [comment]
我这边验证验证了，修改之前mapH，mapW是小于等于scoreH,scoreW的，就像你说的会丢掉一些框，但是我测试那张图人脸居中，最右侧最下下册框丢失，影响不是很大，但如果测试图像最右侧最下侧有人脸的话，会不会就这样丢失了呢？

嗯，你说的问题能理解，确实会带来很大的额外开销。
验证pnet20分支：
修改之前结果如下：
![3](https://user-images.githubusercontent.com/33740622/50732549-43c2b800-11b8-11e9-84ec-d93713831d1c.png)
修改之后结果如下：
![4](https://user-images.githubusercontent.com/33740622/50732557-576e1e80-11b8-11e9-9ce5-1cc7d6244d90.png)
结果分析：
修改之前的结果维度相同，我修改之后的结果维度不同，我修改之后每一种分辨率的mapH多了1个存储空间，再乘以mapW，总共多了mapW个存储空间，你这里做了判断，
![default](https://user-images.githubusercontent.com/33740622/50732601-5093db80-11b9-11e9-8db3-153407418b50.png)

不会蹦的，只是浪费了map的空间
