### ISSUE TITLE
请问 无法打开文件“ZQCNN.lib” 怎么解决？

### ISSUE THREAD

**Issue by queryor** [zuoqing1988/ZQCNN#34]
我使用的环境是win10+VS2015（就是你提供的那个），我在测试使用samplemtcnn的时候出现的问题，请问怎么解决？谢谢了

**Comment by zuoqing1988** [comment]
x64下应该设置好了依赖路径，win32可能没设。你就用x64吧

**Comment by queryor** [comment]
我是设置的X64 的debug模式，但是还是无法打开...是不是这个文件需要自己生成？我查找了文件，只有在 ZQCNN-master\ZQCNN\x64\Debug 有这个文件。

**Comment by zuoqing1988** [comment]
正常情况下直接编译就会链接上。
你从来没写过C++程序？附加库目录，附加依赖项这些不懂吗？

**Comment by queryor** [comment]
已解决.. 打扰大佬了
