### ISSUE TITLE
pnet_stage 返回false

### ISSUE THREAD

**Issue by bigyaofei** [zuoqing1988/ZQCNN#36]
大神，我把算法在linux下重新建了下工程，然后用sampleMTCNN作为demo测试一下，模型加载是成功的，但是mtcnn.find106这步在pnet_stage时候就返回false了，百思不得其解，代码完全照搬没改动过的

**Comment by zuoqing1988** [comment]
测的是4.jpg？

**Comment by zuoqing1988** [comment]
你可以加我QQ 275918592

**Comment by zuoqing1988** [comment]
以上问题是当初ZQCNN不支持linux，用户自己更改代码造成的。
如今ZQCNN已经支持Linux，下载最新代码编译即可。
