### ISSUE TITLE
FacialEmotion caffe model

### ISSUE THREAD

**Issue by WIll-Xu35** [zuoqing1988/ZQCNN#37]
Hi all,

I'm playing with the FacialEmotion caffe model. I can see the input to the network is of dim (10, 1, 42, 42). But the fer2013 dataset seems to have 48x48 images.

Can anyone elaborate what is the input to the model.

Many thanks.

**Comment by zuoqing1988** [comment]
You can design a new net with input 48*48.

**Comment by WIll-Xu35** [comment]
@zuoqing1988 Apart from training a new network, I tested the pretrained FacialEmotion model (by giving it some fake data), but the output stays the same no matter what data I feed to the model.

**Comment by zuoqing1988** [comment]
resize to 42x42
