### ISSUE TITLE
关于mtcnn速度 求助

### ISSUE THREAD

**Issue by queryor** [zuoqing1988/ZQCNN#44]
谢谢大佬的工作。但是我在测试过程中遇见了问题，想求助一下：
1、我在window下 i5-8400 （单线程）测试mtcnn, 640*480（4.jpg） 32ms （以及改了ZQ_CNN_SSETYPE_AVX2为ZQ_CNN_SSETYPE_AVX）不知道这个速度还能加速吗？需要怎么弄？
2、我试图将前两个模型换成你上传的fast版本，然后报模型初始化失败，请问如何解决？

谢谢了

**Comment by zuoqing1988** [comment]
1.如果AVX2能正常运行就用AVX2
2.这CPU超频可以到4.0，如果没打开高性能模式就打开
3.那张图找最小脸20，单线程32ms应该是正常的速度
4.最新的代码默认就是fast的模型，不需要你改什么

**Comment by zuoqing1988** [comment]
我有比fast更快的模型，但是容易漏检。需要在700星的时候才公布。

**Comment by zuoqing1988** [comment]
现在更快的模型也公布了，但是准确度也会下降，请根据实际情况选用。
Pnet20_v00、Pnet16_v0
