### ISSUE TITLE
Can not download model files from Baidu

### ISSUE THREAD

**Issue by thierrypin** [zuoqing1988/ZQCNN#45]
It appears to be impossible for me to download files from Baidu drive. It forces me to download an EXE file, which I can not run because I'm on Linux. (Even if Baidu programs weren't well-known spywares)

Is there another way to download these models?

**Comment by zuoqing1988** [comment]
Someone suggests https://github.com/iikira/BaiduPCS-Go

**Comment by zuoqing1988** [comment]
or https://wiki.deepin.org/wiki/Wine
