### ISSUE TITLE
关于ZQCNN中进行人头检测的模型加载问题

### ISSUE THREAD

**Issue by zeyuanlicbpm** [zuoqing1988/ZQCNN#46]
你公开的进行head检测的zqcnn的模型，包含6个模型文件；我在SampleMTCNN中按照如下顺序加载模型测试，
报错：failed to open file model/headdet1-dw24-fast.zqparams;
加载模型的代码如下：
mtcnn.Init("model/headdet1-dw20-fast.zqparams", "model/headdet1-dw20-fast-16.nchwbin",
		 "model/headdet1-dw24-fast.zqparams", "model/headdet1-dw24-fast-16.nchwbin",
		 "model/headdet1-dw48-fast.zqparams", "model/headdet1-dw48-fast-16.nchwbin",
		 thread_num, false);
请问是什么问题呢？

**Comment by zuoqing1988** [comment]
你看一下文件名有没有写错，第二级应该叫det2,第三级应该叫det3

**Comment by zeyuanlicbpm** [comment]
谢谢哈，大意啦！

**Comment by zeyuanlicbpm** [comment]
你好，你能大致描述一下，日志中的时间分析的意思吗？
rnet = 0.9 M, onet = 3.3 M
convert cost: 0.439 ms  
nms cost: 0.549 ms, (1140-->128)
nms cost: 0.253 ms, (436-->52)
nms cost: 0.045 ms, (94-->10)
nms cost: 0.006 ms, (4-->2)
nms cost: 0.002 ms, (0-->0)
nms cost: 0.001 ms, (0-->0)
nms cost: 0.001 ms, (0-->0)
nms cost: 0.001 ms, (0-->0)
nms cost: 0.001 ms, (0-->0)
nms cost: 0.000 ms, (0-->0)
nms cost: 0.210 ms
first stage candidate count: 192
stage 1: cost 259.647 ms
run Rnet [124] times, candidate after nms: 58
stage 2: cost 24.819 ms
run Onet [58] times, candidate before nms: 37
stage 3: cost 38.825 ms
final found num: 37
total cost: 325.051 ms (P: 260.164 ms, R: 25.587 ms, O: 39.301 ms)
total 3.565 s / 10 = 356.507 ms

**Comment by zuoqing1988** [comment]
rnet = 0.9 M, onet = 3.3 M（模型大小）
convert cost: 0.439 ms（uchar转ZQ_CNN_Tensor4D时间）
nms cost: 0.549 ms, (1140-->128)（每个层次nms时间及框个数，下同）
nms cost: 0.253 ms, (436-->52)
nms cost: 0.045 ms, (94-->10)
nms cost: 0.006 ms, (4-->2)
nms cost: 0.002 ms, (0-->0)
nms cost: 0.001 ms, (0-->0)
nms cost: 0.001 ms, (0-->0)
nms cost: 0.001 ms, (0-->0)
nms cost: 0.001 ms, (0-->0)
nms cost: 0.000 ms, (0-->0)
nms cost: 0.210 ms
first stage candidate count: 192（stage1，nms之后的框个数）
stage 1: cost 259.647 ms
run Rnet [124] times, candidate after nms: 58（真正运行Rnet的个数，部分特别小的或者越界的去掉了）
stage 2: cost 24.819 ms
run Onet [58] times, candidate before nms: 37（真正运行Onet的个数，部分特别小的或者越界的去掉了）
stage 3: cost 38.825 ms
final found num: 37
total cost: 325.051 ms (P: 260.164 ms, R: 25.587 ms, O: 39.301 ms)
total 3.565 s / 10 = 356.507 ms

**Comment by zeyuanlicbpm** [comment]
好的，谢谢！
