### ISSUE TITLE
关于人头检测的参数设置

### ISSUE THREAD

**Issue by zhongwenkun886** [zuoqing1988/ZQCNN#47]
您好，关于人头检测，请问在SampleMTCNN上参数如何设置才能复现项目 train-mtcnn-head 中的图片 head5.jpg 的结果，我是如下设置的，效果很差。
if (!mtcnn.Init("model/headdet1-dw20-fast.zqparams", "model/headdet1-dw20-fast-16.nchwbin",
			"model/headdet2-dw24-fast.zqparams", "model/headdet2-dw24-fast-16.nchwbin",
			"model/headdet3-dw48-fast.zqparams", "model/headdet3-dw48-fast-16.nchwbin", thread_num,false))
		{
			cout << "failed to init!\n";
			return EXIT_FAILURE;
		}

mtcnn.SetPara(image0.cols, image0.rows, 20, 0.4, 0.5, 0.7, 0.4, 0.5, 0.5, 0.709, 3, 20, 2, false);

望指教，谢谢。

**Comment by leiyu1980** [comment]
建议你把测试的图片放几张上来

**Comment by zhongwenkun886** [comment]
> 建议你把测试的图片放几张上来，这样好评估所说的差是什么情况
您好，下面是图片 head5.jpg 的结果。
再次非常感谢您的回复。
![rst](https://user-images.githubusercontent.com/42397285/52832768-f6b9f600-3114-11e9-9409-f91f5cdfe7cd.jpg)

**Comment by zhongwenkun886** [comment]
您好，下面是图片 head5.jpg 的结果。
再次非常感谢您的回复。
![rst](https://user-images.githubusercontent.com/42397285/52832803-1ea95980-3115-11e9-9365-a916af999c83.jpg)

**Comment by zuoqing1988** [comment]
ZQCNN的MTCNN框架与train-mtcnn-head里python代码的逻辑并不一样，所以无论你怎么设置参数也可能无法复现那里面的结果。
不同之处至少有两方面（可能不仅限于此）：
1.stage1找到框之后，python代码会对bbox根据回归值进行修改，而ZQCNN里没有这么做（理由是，很小的模型回归值压根不准，不过这个人头pnet还挺大的）。
2.ZQCNN里MTCNN的nms策略和python代码不一样。

可能还存在计算精度的问题。

另外，由于人头检测模型用的hollywoodheads训练的，这个数据集的样本很局限，很多WIDER训练的人脸检测模型都能检出的人头，用这个人头模型反而检测不出来。所以，如果有自己的人头数据，尽量用自己的数据训练，如果能公布出来，我可以帮你训练，数据用VOC格式就行，我有voc格式转MTCNN训练格式的脚本。

**Comment by zhongwenkun886** [comment]
好的，谢谢。
即 ZQCNN 目前并不适合跑人头检测模型。

**Comment by zuoqing1988** [comment]
我可以给一个还凑合的参数，能检测到93个人头
mtcnn.SetPara(image0.cols, image0.rows, 20, 0.3, 0.6, 0.7, 0.4, 0.5, 0.5, 0.709, 3, 20, 4, special_handle_very_big_face);

**Comment by zuoqing1988** [comment]
我知道了你的参数问题所在，false前的那个参数是stride，人头模型pnet的stride=4.
如果你填成2，会导致所有候选框的位置全是错的。

**Comment by zhongwenkun886** [comment]
好的，非常感谢
