### ISSUE TITLE
可以公开人脸识别训练数据集吗？

### ISSUE THREAD

**Issue by bleakie** [zuoqing1988/ZQCNN#48]
您好，感谢公开优质的代码，请问可以方便公开下训练的数据集吗？

**Comment by zuoqing1988** [comment]
人脸识别模型用insightface训练

**Comment by bleakie** [comment]
请教：就结果来看，感觉和insightface的结果基本差不多，还有什么策略可以提升算法的效果呢？

**Comment by zuoqing1988** [comment]
没啥算法，改改网络就行，也许你运气好能撞上一个又快又好的模型

**Comment by bleakie** [comment]
哈哈哈哈，总觉得这不是终极大招，在图像的尺寸和数据上还有什么文章可以做吗？

**Comment by zuoqing1988** [comment]
这是很专业的问题，图像识别应该基本到瓶颈了，改loss，改网络结构，在同等计算量下，相比目前的insightface都不会有巨大的提升

**Comment by bleakie** [comment]
所以，就目前来说，想提升识别的效果要么在数据集上下工夫，要么提高数据的清晰度？

**Comment by zuoqing1988** [comment]
提高人脸识别准确度只有3条路径：
1.更改loss
2.更改网络
3.更改训练数据
第一条，我认为从softmax到insightface的arcface，提升幅度很大，但是想要进一步提升应该很大
第二条，我认为从VGG到resnet+mobilenet，同等计算量时的模型精度已经挖掘得差不多了
第三条，训练数据必须要和实际应用场合匹配，才能达到理想的精度，比如你想要夜间红外场景的识别精度，但是用网上开源的图片去训练，随便想想都觉得是不可能的。再比如你拿老外的图片训练，然后用于识别中国人，这也会导致使用时的精度比训练时精度低得多。

**Comment by bleakie** [comment]
说的很有道理，就我目前的测试来看，发现比arcface更优的loss策略还没有见到，前面两个策略我都有尝试，发觉已经挖掘到了max，所以目前只能在数据集上做手段。
感谢您的耐心指导（手动握手）

**Comment by wu1995snow** [comment]
请教个问题，训练一个人脸识别模型大致需要多少人多少张图象

**Comment by zuoqing1988** [comment]
> 请教个问题，训练一个人脸识别模型大致需要多少人多少张图象

insightface里有训练代码和训练集，其中glint360k数据集有36万人，接近两千万张图
