### ISSUE TITLE
landmark106 convert to ncnn Error

### ISSUE THREAD

**Issue by zhanglaplace** [zuoqing1988/ZQCNN#50]
你好，landmark的106点的模型转化为ncnn，出现了未定义的层，查看json应该是这个地方的问题
![image](https://user-images.githubusercontent.com/12178974/53281800-8b51d300-3769-11e9-9b4a-e6d6c94acafc.png)
请教下左博，这个是不是需要在mxnet中添加你实现的这两个层

**Comment by zuoqing1988** [comment]
最后一层叫bn6_3,后面的手工删掉即可

**Comment by zuoqing1988** [comment]
删转之后的param文件里的最后几层，虽然提示有不支持的层，但是权重已经转出来了。

**Comment by zhanglaplace** [comment]
@zuoqing1988 好的，多谢左博。

**Comment by zhanglaplace** [comment]
@zuoqing1988 这边模型转化了，输出了212维度的特征结果，但是目前还是有两个方向不是很确定：
1、输入图像的mean和val 是根据图像计算还是设置为一个常数了。
2、输出的结果好像还有负数，而且48的size还要大。这个值是如何与人脸框或者与48的输入对应的。
![image](https://user-images.githubusercontent.com/12178974/53544544-61315400-3b61-11e9-83b3-7179576349f8.png)

**Comment by zuoqing1988** [comment]
mean=-127.5, val=1.0/128
先跑通ZQCNN/SamplesZQCNN/SampleLnet106

**Comment by zhanglaplace** [comment]
@zuoqing1988 嗯，成功跑通了，测试了效果，一般情况下很赞，光照差的时候不是特别准。不过速度是真的快 👍

**Comment by 1976277169** [comment]
> 
> 
> @zuoqing1988 嗯，成功跑通了，测试了效果，一般情况下很赞，光照差的时候不是特别准。不过速度是真的快 +1

能够分享一下你调用的代码吗？我这边也输出很多负数坐标~

**Comment by 1976277169** [comment]
> 
> 




> 
> 
> > @zuoqing1988 嗯，成功跑通了，测试了效果，一般情况下很赞，光照差的时候不是特别准。不过速度是真的快 +1
> 
> 能够分享一下你调用的代码吗？我这边也输出很多负数坐标~

解决了~

**Comment by 407257625** [comment]
@1976277169  能分享代码吗？

**Comment by MirrorYuChen** [comment]
> @1976277169 能分享代码吗？
我贴在我的博客上了~
https://blog.csdn.net/sinat_31425585/article/details/89104728#commentsedit

**Comment by Tomhouxin** [comment]
如何转成ncnn模型？

**Comment by MirrorYuChen** [comment]
> 如何转成ncnn模型？
https://github.com/zuoqing1988/ZQCNN/issues/64

**Comment by Tomhouxin** [comment]
@1976277169 ,看了这个，还是不会改。
问题一：左博说的去掉后面不要的层，并不知道哪些不要呀。还有后面的数字不知道是什么意思，如下：
![image](https://user-images.githubusercontent.com/23637856/56649786-62da4c80-66b8-11e9-8e8c-f4df067e5595.png)
问题二：是不是只要改params文件，bin文件不需要改吗？

**Comment by zuoqing1988** [comment]
如果你都不知道哪些layer有用哪些没用，你怎么玩的转深度学习?转什么框架你总得知道对该框架有点了解吧？

**Comment by MirrorYuChen** [comment]
可以去好好研究一下ncnn的wiki，这个很重要~

**Comment by Tomhouxin** [comment]
非常感谢，很受益，一个人自学，找不到方向，只有脸皮厚点找你们这些前辈指指方向

**Comment by MirrorYuChen** [comment]
晚点我把代码和模型一起上传一下吧~😂😂😂😂，方便大家学习~

**Comment by Tomhouxin** [comment]
恩恩，可以发个链接在这里，昨晚研究了一波，找到了些灵感

**Comment by MirrorYuChen** [comment]
> 恩恩，可以发个链接在这里，昨晚研究了一波，找到了些灵感

https://github.com/MirrorYuChen/ncnn_106landmarks.git

**Comment by aidlearning** [comment]
https://github.com/aidlearning/AidLearning-FrameWork/tree/master/examples/landmark106
