### ISSUE TITLE
Speed question about MTCNN

### ISSUE THREAD

**Issue by Steven9402** [zuoqing1988/ZQCNN#51]
Thanks for your work!
  I tested SamplePet on Company's i7 server PC. It costs 300ms/frame for 'det1.zqparams' and 100ms for 'det1_dw20_fast.zqparams'. While on the same server PC, the original MTCNN runs 20ms/frame. Did I make some mistakes? HELP!

**Comment by Steven9402** [comment]
and The image is size is data/4.jpg which is of 640*480 size. The printed 'num_MulAdd' is 11.6 M for 'det1_dw20_fast.zqparams',  0.0 M for det1.zqparams.

**Comment by zuoqing1988** [comment]
(1)SamplePnet doesn't specify min_size。 It equals 640*480 find min_size=12 for det1.zqparams and min_size=20 for det1_dw20_fast.zqparams.
(2)Try SampleMTCNN and make sure min_size be the same.
(3)In line 1 of det1.zqparams, add H=144 W=192

**Comment by Steven9402** [comment]
The problem is solved. Thanks!
