### ISSUE TITLE
ZQ_CNN_Tensor4D.h中ROI函数93行疑问

### ISSUE THREAD

**Issue by DWxqs** [zuoqing1988/ZQCNN#53]
使用您代码时debug到的一个小问题，memset(dst_slice_ptr - dstPixelStep*dst_borderW + dstWidthStep*dst_borderH, 0, sizeof(float)*dstWidthStep*dst_borderH);这行加Pad高方向指错位置了吧不应该是ROI区域的下沿么？

**Comment by zuoqing1988** [comment]
因为那个dst_slice_ptr指向的是pad之前的第一个像素，pad之后指针地址也没变，真正变的时候是在ZQ_CNN_Forward_SSEUtils里了，比如你可以看看
ZQ_CNN_Forward_SSEUtils::ConvolutionWithBias

**Comment by DWxqs** [comment]
是的，dst_slice_ptr是ROI区域的首地址，然后dst_slice_ptr - dstPixelStep * dst_borderW向左挪了dst_borderW，然后dst_slice_ptr - dstPixelStep * dst_borderW + dstWidthStep * dst_borderH只继续向下挪了dst_borderH，不应该是向下挪ROI区域的height么，然后ROI区域下面再加个dst_borderH数量的行(置零)；我看到#92行就是对ROI的上面添加了dst_borderH数量的行啊

**Comment by zuoqing1988** [comment]
感谢你提出这个问题，这确实是个BUG。这条路径可能从来没执行过，所有一直没有发现错误。

**Comment by zuoqing1988** [comment]
你可以进这个QQ群347185749，这样交流起来会及时一些。

**Comment by DWxqs** [comment]
貌似我好像在群里，只是不常用QQ
