### ISSUE TITLE
请问1路1080p的视频流占用的CPU资源有多少？

### ISSUE THREAD

**Issue by guoguangchao** [zuoqing1988/ZQCNN#59]
请问1路1080p的视频流占用的CPU资源有多少，一个i7  8核的处理器大约能实时检测几路1080p的视频呢，谢谢！

**Comment by zuoqing1988** [comment]
没有测过视频解码，但是根据一般经验，一个线程单独用来解1080P应该来得及。至于检测的话，看你是否跳帧，1080P如果检测最小100像素，脸少的情况下，可以做到20ms内，如果你一秒只取一帧的话，把待检测图片排个队，用一个线程就足够了。

**Comment by zuoqing1988** [comment]
一线程解一路来得及。

**Comment by guoguangchao** [comment]
好的，谢谢回复！！
