### ISSUE TITLE
使用mxnet载入关键点定位模型报错。

### ISSUE THREAD

**Issue by 1976277169** [zuoqing1988/ZQCNN#69]
左博士，您好，我想尝试一下使用mxnet对您提供的mxnet模型进行载入，mxnet版本为1.2.0cpu版本，结果报了个错误：
Traceback (most recent call last):
File "compile.py", line 10, in 
sym, arg_params, aux_params = mx.model.load_checkpoint(prefix, epoch)
File "/home/mirror/.conda/envs/tf/lib/python3.5/site-packages/mxnet/model.py", line 419, in load_checkpoint
symbol = sym.load('%s-symbol.json' % prefix)
File "/home/mirror/.conda/envs/tf/lib/python3.5/site-packages/mxnet/symbol/symbol.py", line 2535, in load
check_call(_LIB.MXSymbolCreateFromFile(c_str(fname), ctypes.byref(handle)))
File "/home/mirror/.conda/envs/tf/lib/python3.5/site-packages/mxnet/base.py", line 149, in check_call
raise MXNetError(py_str(_LIB.MXGetLastError()))
mxnet.base.MXNetError: [03:34:34] src/operator/custom/custom.cc:104: Check failed: CustomOperator::Get()->Find(params.op_type) != nullptr Cannot find custom operator negativemining_onlylandmark106

载入代码如下：
import mxnet as mx
from mxnet import ndarray as nd

prefix, epoch = "lnet106-big", 0
sym, arg_params, aux_params = mx.model.load_checkpoint(prefix, epoch)
image_size = (48, 48)
opt_level = 3

shape_dict = {'data':(1, 3, *image_size)}
nnvm_sym, nnvm_params = nnvm.frontend.from_mxnet(sym, arg_params, aux_params)

您能提供一下帮助吗？谢谢左博啦~

**Comment by 1976277169** [comment]
问题已经解决，谢谢左博提供的模型~

**Comment by zhuoyue0515** [comment]
您好，请问您一下怎么解决的

> 问题已经解决，谢谢左博提供的模型~

**Comment by zhuoyue0515** [comment]
> 问题已经解决，谢谢左博提供的模型~

您好，请问一下您怎么解决的

**Comment by 407257625** [comment]
@1976277169  请问你是怎么解决的啊？ 使用mxnet python时也出现这种情况

**Comment by weihua04** [comment]
@1976277169 @zuoqing1988  我也遇到了相同的问题，“Check failed: CustomOperator::Get()->Find(params.op_type) != nullptr Cannot find custom operator negativemining”，请问下是怎么解决的呢？非常感谢

**Comment by zuoqing1988** [comment]
可能symbol变了吧。

**Comment by MirrorYuChen** [comment]
过几天出一个landmark， tvm的模型集，转换过程和转换ncnn差不多~

**Comment by MirrorYuChen** [comment]
过几天出一个landmark， tvm的模型集，转换过程和转换ncnn差不多~

**Comment by MirrorYuChen** [comment]
模型和测试代码已经上传，请感兴趣的小伙伴测试一下：https://github.com/MirrorYuChen/tvm_106landmarks.git

**Comment by SteveJRZ** [comment]
请问这个问题是怎么解决的

**Comment by SteveJRZ** [comment]
请问这个问题是怎么解决的 @1976277169

**Comment by Sun-ch122** [comment]
negativemining_onlylandmark106 问题
在作者github主页找mtcnn_train这个项目就能找到这个函数

**Comment by yang-ruixin** [comment]
以前从没用过mxnet，可以提供完整的mxnet python的前向推理代码吗，对我入门会很有帮助，谢谢@1976277169
