### ISSUE TITLE
关于landmark与人脸对齐

### ISSUE THREAD

**Issue by xiaozhuka** [zuoqing1988/ZQCNN#73]
请教两个问题：
1. landmark对检测框的要求严格吗？我认为比较大具体表现在两个方面
1）增加shift扰动比较大的话，我训练出来的模型很难收敛
2）使用mobilenetssd训练的人脸检测器检测得到landmark模型，使用yolov3训练的人脸检测器检测，效果差很多。两个检测器模型都是在widerface数据集训练得到的
请问你有没有遇到这种情况或者你对这个问题怎么看

2. 人脸对齐除了仿射变换有没有其他办法？可以使用模型做端到端的检测吗？输入人脸图像输出对齐后的人脸图像

**Comment by zuoqing1988** [comment]
框的范围越大（太大或者太小），用同一个模型的训练出来的精度会越低，因而需要根据检测器的实际情况反复调整训练landmark时的采样框。
用5点做变换是通用做法，如果你要搞新方法，你的人脸识别训练也得改，整个工程下来你要做的东西就太多了。

**Comment by xiaozhuka** [comment]
人脸识别的训练数据不是对齐之后的人脸吗？我是想把关键点检测与人脸对齐做成一个模型，不要基于5点仿射变换的对齐操作

**Comment by zuoqing1988** [comment]
你怎么为每张人脸生成对齐后的图片，没有groundtruth怎么训练？
如果你还是用5点生成的，那从信息量上来说起码是没有任何增加，实际效果就是严重倒退，从一堆离散的像素信息中学到一个五点的变换公式，而且还拟合得不好。

**Comment by xiaozhuka** [comment]
嗯，你说的很对，没有训练数据可能会是限制训练的主要因素
