### ISSUE TITLE
voc-mobilenetssd的检测问题

### ISSUE THREAD

**Issue by hlcool** [zuoqing1988/ZQCNN#75]
左博，您好：
      我在用您的ZQCNN来部署mobilenet-ssd时，检测结果什么都没有，因此想向您咨询一下。

      首先我直接跑了您的SamplesZQCNN文件夹下面的SampleSSD例子，我主要做了如下修改：
      1、修改图像源，取消注释39行，注释掉40行
      2、无需进行通道转换，注释48行，取消注释49行
      3、更改模型为voc-mobilenetssd  56行和57行
      4、修改检测类别 83和88行

编译通过后执行检测，但是无结果输出，不知道什么原因？
最后显示的图片无任何检测框。

[我的模型是下载的您已经转换好的voc-mobilenetssd，](https://pan.baidu.com/s/1cyly_17cTOJBaCRiiQtWkQ#list/path=%2F)

我的环境是：Ubuntu16.04

还请左博指导一下具体问题出在哪里？非常感谢

**Comment by zuoqing1988** [comment]
先找个windows机器试试，报的那些in Layer conv0之类的是不正常的，不过也有其他人报这些。我自己也很久没在Linux上跑过了，可能是编译器或者cmake之类的原因，具体情况你自己对照windows调试吧

**Comment by hlcool** [comment]
问题解决，感谢左博。
左博的模型参数文件是在Windows下面转换的，文本文件Linux和Windows之间是有差别的，因此需要转一下。可以直接用vim转
vim MobileNetSSD_deploy.zqparams
:set fileformat=unix
：wq

完美解决
