### ISSUE TITLE
请教1：n分值拉不开的问题？

### ISSUE THREAD

**Issue by bleakie** [zuoqing1988/ZQCNN#79]
在进行1：n的测试时，当底库数量>1000的时候，同一人和其他人的得分拉不开，请问如何解决呢？

**Comment by zuoqing1988** [comment]
1.用更大的模型
2.每个人用更多的图片

**Comment by bleakie** [comment]
1.如果我只有每个人的一张图片呢？
2.更大的模型是指什么意思？

**Comment by zuoqing1988** [comment]
resnet-101,resnet-251等等

**Comment by bleakie** [comment]
我现在使用的就是resnet-101，底库是证件照，在现实照片和其比对时会出现分值拉不开，然后很难设置阈值的问题

**Comment by bleakie** [comment]
在进行1：1和1：n的测试的时候，是否需要两种策略的训练模式呢？

**Comment by zuoqing1988** [comment]
那也是没有办法的问题

**Comment by bleakie** [comment]
我听说云从在训练这两种场景的时候采用的就是两种策略
