### ISSUE TITLE
Fail to load the model for head detection MTCNN ZQCNN

### ISSUE THREAD

**Issue by rena-ganba** [zuoqing1988/ZQCNN#88]
Hi Zuoqing,

I try to load the head detection model as follows:

if (!mtcnn.Init("../../model/headdet1-dw20-fast.zqparams", "../../model/headdet1-dw20-fast-16.nchwbin","../../model/headdet2-dw24-fast.zqparams", "../../model/headdet2-dw24-fast-16.nchwbin","../../model/headdet3-dw48-fast.zqparams", "../../model/headdet3-dw48-fast-16.nchwbin", thread_num,false))
			{
				cout << "failed to init!\n";
				return EXIT_FAILURE;
			}
		}
mtcnn.SetPara(640, 480, 20, 0.3, 0.6, 0.7, 0.4, 0.5, 0.5, 0.709, 3, 20, 4, special_handle_very_big_face);

But the problem is it gives output like this:

release$ ./SampleMTCNN 
 in Layer conv1n para bias
 in Layer conv2_dwara bias
 in Layer conv2_sepra bias
 in Layer conv3_dwara bias
 in Layer conv3_sepra bias
 in Layer conv4_dwara bias
 in Layer conv4_sepra bias
 in Layer conv4_1para bias
 in Layer bn4_1n para bias
 in Layer conv4_2para bias
 in Layer bn4_2n para bias
 in Layer conv1n para bias
 in Layer conv2_sepra bias
 in Layer conv3_sepra bias
 in Layer conv4_dwara bias
 in Layer conv4_sepra bias
 in Layer conv5_dwara bias
 in Layer conv5_sepra bias
 in Layer conv5_1para bias
 in Layer bn5_1n para bias
 in Layer conv5_2para bias
 in Layer bn5_2n para bias
 in Layer conv1n para bias
 in Layer conv2_sepra bias
 in Layer conv3_dwara bias
 in Layer conv3_sepra bias
 in Layer conv4_dwara bias
 in Layer conv4_sepra bias
 in Layer conv5_dwara bias
 in Layer conv5_sepra bias
 in Layer conv6_1para bias
 in Layer bn6_1n para bias
 in Layer conv6_2para bias
 in Layer bn6_2n para bias
rnet = 0.9 M, onet = 3.5 M
Segmentation fault (core dumped)

How can it happens?

Thank you

**Comment by zuoqing1988** [comment]
https://github.com/zuoqing1988/ZQCNN/issues/75

**Comment by rena-ganba** [comment]
Thank you very much for pointing out the fileformat UNIX solution.
After I change the file format to UNIX, it does run but I got following strange behavior:

rnet = 1.0 M, onet = 3.6 M
convert cost: 3.026 ms
Pnet [0]: resolution [640x480], resize:0.000 ms, cost:127.620 ms
Pnet [1]: resolution [454x341], resize:0.991 ms, cost:54.073 ms
Pnet [2]: resolution [322x242], resize:0.597 ms, cost:23.028 ms
Pnet [3]: resolution [229x172], resize:0.228 ms, cost:9.538 ms
Pnet [4]: resolution [162x122], resize:0.169 ms, cost:4.419 ms
Pnet [5]: resolution [115x86], resize:0.122 ms, cost:2.010 ms
Pnet [6]: resolution [82x61], resize:0.075 ms, cost:0.961 ms
Pnet [7]: resolution [58x44], resize:0.048 ms, cost:0.468 ms
Pnet [8]: resolution [41x31], resize:0.024 ms, cost:0.208 ms
Pnet [9]: resolution [29x22], resize:0.013 ms, cost:0.098 ms
Pnet [10]: resolution [27x20], resize:0.009 ms, cost:0.077 ms
nms cost: 0.019 ms, (0-->0)
nms cost: 0.009 ms, (0-->0)
nms cost: 0.004 ms, (0-->0)
nms cost: 0.002 ms, (0-->0)
nms cost: 0.001 ms, (0-->0)
nms cost: 0.001 ms, (0-->0)
nms cost: 0.000 ms, (0-->0)
nms cost: 0.000 ms, (0-->0)
nms cost: 0.000 ms, (0-->0)
nms cost: 0.000 ms, (0-->0)
nms cost: 0.000 ms, (0-->0)
convert cost: 0.915 ms
Pnet [0]: resolution [640x480], resize:0.000 ms, cost:106.199 ms
Pnet [1]: resolution [454x341], resize:0.440 ms, cost:47.608 ms
Pnet [2]: resolution [322x242], resize:0.345 ms, cost:20.650 ms
Pnet [3]: resolution [229x172], resize:0.272 ms, cost:9.299 ms
Pnet [4]: resolution [162x122], resize:0.160 ms, cost:4.322 ms
Pnet [5]: resolution [115x86], resize:0.115 ms, cost:2.042 ms
Pnet [6]: resolution [82x61], resize:0.081 ms, cost:0.956 ms
Pnet [7]: resolution [58x44], resize:0.047 ms, cost:0.468 ms
Pnet [8]: resolution [41x31], resize:0.022 ms, cost:0.202 ms
Pnet [9]: resolution [29x22], resize:0.013 ms, cost:0.097 ms
Pnet [10]: resolution [27x20], resize:0.009 ms, cost:0.078 ms
nms cost: 0.021 ms, (0-->0)
nms cost: 0.010 ms, (0-->0)
nms cost: 0.003 ms, (0-->0)
nms cost: 0.002 ms, (0-->0)
nms cost: 0.001 ms, (0-->0)
nms cost: 0.000 ms, (0-->0)
nms cost: 0.000 ms, (0-->0)
nms cost: 0.000 ms, (0-->0)
nms cost: 0.000 ms, (0-->0)
nms cost: 0.000 ms, (0-->0)
nms cost: 0.000 ms, (0-->0)
convert cost: 0.911 ms
Pnet [0]: resolution [640x480], resize:0.000 ms, cost:103.410 ms
Pnet [1]: resolution [454x341], resize:0.438 ms, cost:46.937 ms
Pnet [2]: resolution [322x242], resize:0.343 ms, cost:20.780 ms
Pnet [3]: resolution [229x172], resize:0.232 ms, cost:9.255 ms
Pnet [4]: resolution [162x122], resize:0.161 ms, cost:4.271 ms
Pnet [5]: resolution [115x86], resize:0.111 ms, cost:2.023 ms
Pnet [6]: resolution [82x61], resize:0.081 ms, cost:0.955 ms
Pnet [7]: resolution [58x44], resize:0.046 ms, cost:0.470 ms
Pnet [8]: resolution [41x31], resize:0.022 ms, cost:0.201 ms
Pnet [9]: resolution [29x22], resize:0.013 ms, cost:0.095 ms
Pnet [10]: resolution [27x20], resize:0.010 ms, cost:0.077 ms
nms cost: 0.020 ms, (0-->0)
nms cost: 0.009 ms, (0-->0)
nms cost: 0.004 ms, (0-->0)
nms cost: 0.002 ms, (0-->0)
nms cost: 0.001 ms, (0-->0)
nms cost: 0.000 ms, (0-->0)
nms cost: 0.000 ms, (0-->0)
nms cost: 0.000 ms, (0-->0)
nms cost: 0.000 ms, (0-->0)
nms cost: 0.000 ms, (0-->0)
nms cost: 0.000 ms, (0-->0)
convert cost: 0.913 ms
.
.
.
looping forever

What does happen? It seems the P-Net fails somehow

**Comment by zuoqing1988** [comment]
try to change "LoadFrom(...., true, 1e-9, true)" to "LoadFrom(...., false,1e-9,false)" for all nets

https://github.com/zuoqing1988/ZQCNN/blob/366905a7e239ea3297b6f4cbe87218f7598fdb2b/ZQCNN/ZQ_CNN_MTCNN.h#L101

**Comment by rena-ganba** [comment]
Thank you very much, by setting merge-bn etc to false, it now runs well
