### ISSUE TITLE
请问ZQCNN中有参数能控制识别人脸的数量吗

### ISSUE THREAD

**Issue by linsinan1995** [zuoqing1988/ZQCNN#91]
找了挺久都没看到，只好麻烦下您

**Comment by zuoqing1988** [comment]
https://github.com/zuoqing1988/ZQCNN/blob/366905a7e239ea3297b6f4cbe87218f7598fdb2b/SamplesZQCNN/SampleMTCNN/SampleMTCNN.cpp#L137

**Comment by linsinan1995** [comment]
非常感谢！
