### ISSUE TITLE
Winograd implementation

### ISSUE THREAD

**Issue by rena-ganba** [zuoqing1988/ZQCNN#94]
Dear ZQ, 

Have you implemented winograd? I haven't seen the winograd implementation yet in your code. If I want to implement it, where should I put the winograd?

Thank you

**Comment by zuoqing1988** [comment]
Winograd is useless for depthwise convolution。As ZQCNN is designed to run on CPU, models should be always trained with dw+sep structures for commercial consideration。

**Comment by rena-ganba** [comment]
well, thank you for the information. Before, it bothered me why you did not implemenr winograd. Now it becomes clear.

Your zqnn lib is really wonderful
