### ISSUE TITLE
无法在pc ubuntu16.04和树莓派上编译通过

### ISSUE THREAD

**Issue by CharlieXie** [zuoqing1988/ZQCNN#95]
1. 按照build-with-cmake.md文档中不走，在树莓派上无openblas 编译 make SampleMatMulNEON、make SampleMTCNN、make SampleSphereFaceNet均报错
`[  2%] Building C object ZQ_GEMM/CMakeFiles/ZQ_GEMM.dir/math/zq_gemm_32f_align_c.c.o
In file included from /usr/include/features.h:388:0,
                 from /usr/include/stdlib.h:24,
                 from /home/pi/ZQCNN-master/ZQCNN/ZQ_CNN_CompileConfig.h:3,
                 from /home/pi/ZQCNN-master/ZQ_GEMM/math/zq_gemm_32f_align_c.c:1:
/usr/include/arm-linux-gnueabihf/gnu/stubs.h:7:29: fatal error: gnu/stubs-soft.h: No such file or directory
/ # include <gnu/stubs-soft.h>
compilation terminated.
ZQ_GEMM/CMakeFiles/ZQ_GEMM.dir/build.make:62: recipe for target 'ZQ_GEMM/CMakeFiles/ZQ_GEMM.dir/math/zq_gemm_32f_align_c.c.o' failed
make[3]: *** [ZQ_GEMM/CMakeFiles/ZQ_GEMM.dir/math/zq_gemm_32f_align_c.c.o] Error 1
CMakeFiles/Makefile2:85: recipe for target 'ZQ_GEMM/CMakeFiles/ZQ_GEMM.dir/all' failed
make[2]: *** [ZQ_GEMM/CMakeFiles/ZQ_GEMM.dir/all] Error 2
CMakeFiles/Makefile2:920: recipe for target 'SamplesZQCNN/CMakeFiles/SampleMTCNN.dir/rule' failed
make[1]: *** [SamplesZQCNN/CMakeFiles/SampleMTCNN.dir/rule] Error 2
Makefile:365: recipe for target 'SampleMTCNN' failed
make: *** [SampleMTCNN] Error 2`

arm: arm7  32位
系统：Raspbian stretch
cmake 版本：3.7.2
gcc/g++  version 6.3.0 20170516 (Raspbian 6.3.0-18+rpi1+deb9u1)

2. 在ubuntu16.04上编译报错
`media/omnisky/643091a5-cc66-41b1-9245-8ffcd6a5f7df/xcl/ZQCNN-master/3rdparty/include/ZQlib/ZQ_MathBase.h:1122:42: error: there are no arguments to ‘_strcmpi’ that depend on a template parameter, so a declaration of ‘_strcmpi’ must be available [-fpermissive]
   if (_strcmpi(typeid(T).name(), "double") == 0)
                                          ^
/media/omnisky/643091a5-cc66-41b1-9245-8ffcd6a5f7df/xcl/ZQCNN-master/3rdparty/include/ZQlib/ZQ_MathBase.h:1122:42: note: (if you use ‘-fpermissive’, G++ will accept your code, but allowing the use of an undeclared name is deprecated)
`

**Comment by zuoqing1988** [comment]
第一个问题不详，可能是编译器的问题
第二个问题，把_strcmpi改成strcmp应该就行了。ZQlib里的.h都是在windows写的，里面用了很多VC才有的函数

**Comment by CharlieXie** [comment]
@zuoqing1988 左博士您好，
之前的问题1 针对树莓派修改-mfloat-abi=softfp 为-mfloat-abi=hard，之前的问题2按您所说可以解决，但是之后又遇到了下面的错误：
`/media/omnisky/643091a5-cc66-41b1-9245-8ffcd6a5f7df/xcl/ZQCNN-master/SamplesZQCNN/SampleBLISLAB/bl_sgemm_opt_4x4.c:36:29: fatal error: arm_neon.h: No such file or directory
compilation terminated.
SamplesZQCNN/CMakeFiles/SampleBLISLAB.dir/build.make:62: recipe for target 'SamplesZQCNN/CMakeFiles/SampleBLISLAB.dir/SampleBLISLAB/bl_sgemm_opt_4x4.c.o' failed
make[2]: *** [SamplesZQCNN/CMakeFiles/SampleBLISLAB.dir/SampleBLISLAB/`

另外我还有两个问题想向您请教一下：
1. 在运行SampleMTCNN是，106个人脸特征点整体发生了一定角度的偏移，用的是最新发布的模型det5-dw112，如下图
![WechatIMG377](https://user-images.githubusercontent.com/20149037/58934878-4d1f7300-879e-11e9-8227-e01c08f53ef8.jpeg)
请问这是什么原因？
2. 运行SampleMTCNN使用其中的默认模型的时候，使用mtcnn.SetPara设置最小人脸参数为30，并不能检测到48*48像素的人脸。请问默认的模型是否能识别该尺寸的人脸，或者是不是还有哪里需要设置或者替换模型？

**Comment by zuoqing1988** [comment]
凑合用就行

**Comment by CharlieXie** [comment]
哈，@zuoqing1988 感谢您对开源作出的贡献:heart:。出现这个错`arm_neon.h: No such file or directory compilation terminated. `如何解决呢？

**Comment by zuoqing1988** [comment]
arm上本身就带那个头文件

**Comment by zuoqing1988** [comment]
把你上面那个原图发出来，我试试到底啥问题

**Comment by CharlieXie** [comment]
这个错误是在PC上面报的。
这张是320X240
![240P](https://user-images.githubusercontent.com/20149037/58936517-822dc480-87a2-11e9-898d-ee80313609ee.jpg)
这张是160X120（face大小约为48*48）
![120P](https://user-images.githubusercontent.com/20149037/58936623-be612500-87a2-11e9-98c0-db8c013aa3da.jpg)

感谢左博时间🙏

**Comment by zuoqing1988** [comment]
![result1](https://user-images.githubusercontent.com/20920889/58937004-c2da0d80-87a3-11e9-9a85-b2bb9b68063d.png)
![result2](https://user-images.githubusercontent.com/20920889/58937005-c2da0d80-87a3-11e9-874f-c86a094f6253.png)

都是找最小20，其他参数用默认的，106模型用det5-dw112
